import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {As, ChakraProvider, Container, Flex, Link} from '@chakra-ui/react'
import {StoreProvider} from '@/store/StoreProvider'
import NextLink from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Smartsupp test app',
  description: 'Generated by create next app',
}

const Layout = ({ children, }: {
  children: React.ReactNode,
}) => (
    <html lang="en">
        <body className={inter.className}>
            <StoreProvider>
                <ChakraProvider>
                    <Container maxW='3xl'py={10}>
                        <Flex gap={4} pb={6}>
                            <Link as={NextLink as As} href='/'>Home</Link>
                            <Link as={NextLink as As} href='/users'>Users</Link>
                        </Flex>
                        {children}
                    </Container>
                </ChakraProvider>
            </StoreProvider>
        </body>
    </html>
)

export default Layout